package com.hand.Entity;
// Generated 2015-9-21 1:02:26 by Hibernate Tools 3.4.0.CR1

/**
 * Priceconfig generated by hbm2java
 */
public class Priceconfig implements java.io.Serializable {

	private Integer priceConfigId;
	private Customer customer;
	private String custCode;
	private String type;
	private String displayName;
	private String priveListCol;
	private Integer excelCol;
	private String activity;

	public Priceconfig() {
	}

	public Priceconfig(Customer customer, String custCode, String type, String priveListCol, String activity) {
		this.customer = customer;
		this.custCode = custCode;
		this.type = type;
		this.priveListCol = priveListCol;
		this.activity = activity;
	}

	public Priceconfig(Customer customer, String custCode, String type, String displayName, String priveListCol,
			Integer excelCol, String activity) {
		this.customer = customer;
		this.custCode = custCode;
		this.type = type;
		this.displayName = displayName;
		this.priveListCol = priveListCol;
		this.excelCol = excelCol;
		this.activity = activity;
	}

	public Integer getPriceConfigId() {
		return this.priceConfigId;
	}

	public void setPriceConfigId(Integer priceConfigId) {
		this.priceConfigId = priceConfigId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getCustCode() {
		return this.custCode;
	}

	public void setCustCode(String custCode) {
		this.custCode = custCode;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getPriveListCol() {
		return this.priveListCol;
	}

	public void setPriveListCol(String priveListCol) {
		this.priveListCol = priveListCol;
	}

	public Integer getExcelCol() {
		return this.excelCol;
	}

	public void setExcelCol(Integer excelCol) {
		this.excelCol = excelCol;
	}

	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

}
